version: "3"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: lamin
      POSTGRES_PASSWORD: lamin_pw
      POSTGRES_DB: lamindb
    ports:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # minio:
  #   image: minio/minio:latest
  #   environment:
  #     - MINIO_ROOT_USER=lamin
  #     - MINIO_ROOT_PASSWROD=lamin_pw
  #   volumes:
  #     - ./volumes/minio:/data
  #   command: "minio server /data --console-address :9090"
  #   ports:
  #     - 9090
  #     - 9001
  lamin:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/lamin
