version: "3"

services:
  lamin:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    environment:
      - GRANT_SUDO=yes
      - LAMINDB_PASSWORD
      # - AWS_PROFILE=lamin  # can't find the profile
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_CREDENTIAL_EXPIRATION
    volumes:
      - ./:/home/jovyan
      - ~/.aws:/home/jovyan/.aws
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - 8888:8888
